
version: '3'

services:
  api:
    build: api
      # context: .
      # dockerfile: Dockerfile
    container_name: api_bot
    hostname: api_bot
    ports:
      - 3000:3000
    volumes:
      - ./api/.env:/app/.env
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/db_pm 
      - SELENIUM_URL = http://selenium:4444
    depends_on:
      - db
      - selenium

  db:
    image: mongo:latest
    container_name: db_bot
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=db_pm
    volumes:
      - dbdata:/data/db

  
  selenium:
    image: seleniarm/standalone-chromium:4.1.1-alpha-20220119
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
  
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped     # or "always"
    command: /bin/sh -c "nginx -g 'daemon off;'"

volumes:
  dbdata:


