version: '3'

services:
  api:
    build: api
    container_name: apec_bot
    hostname: apec_bot
    ports:
      - 3000:3000
    volumes:
      - ./api/.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=Asia/HoChiMinh
      - MONGODB_URI=mongodb://db:27017/db_pm 
      - SELENIUM_URL = http://selenium:4444
    depends_on:
      - db
      - selenium
    networks:
      - apec_bot

  db:
    image: mongo:latest
    container_name: db_bot
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/HoChiMinh
      - MONGO_INITDB_DATABASE=db_pm
    volumes:
      - dbdata:/data/db
    networks:
      - apec_bot
  
  selenium:
    image: selenium/standalone-chrome:112.0
    container_name: selenium
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - TZ=Asia/HoChiMinh
    networks:
      - apec_bot

  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./web/public:/usr/share/nginx/html
      - ./web/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped     # or "always"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    environment:
      - TZ=Asia/HoChiMinh
    networks:
      - apec_bot

networks:
  apec_bot:
    external: true
    name: apec_bot

volumes:
  dbdata:


