export enum ENUM_STOCK_STATUS_CODE_ERROR {
    STOCK_IS_INACTIVE_ERROR = 5500,
    STOCK_NOT_FOUND_ERROR = 5501,
    STOCK_EXIST_ERROR = 5502,
    STOCK_ACTIVE_ERROR = 5503,
    STOCK_USED_ERROR = 5504,
}
